FROM      jekyll-and-node

WORKDIR   /home
RUN 	  git clone https://github.com/OWASP/owasp-summit-2017.git                            # clone repo with owasp summit site
WORKDIR   owasp-summit-2017
RUN       npm install --quiet                                                                 # update node dependencies

